nodeshift/nodeshift

bin/cli.js, lib/nodeshift-config.js, lib/resource-loader.js, test/resource-loader-test.js
Also, there is a better error message if there isn't a .nodeshift directory
connects to #19
just want to add a test to this also
=> the default is now .nodeshift to put your resource files in

.eslintrc.json, README.md, bin/nodeshift, lib/nodeshift-config.js, package-lock.json, package.json
* Adds an option '--osc.strictSSL' which gets passed to the Openshift rest client. switch to false if using a self-signed cert
* can also be passed in as an option when using the API 'options.osc.strictSSL'
connects to #29
=> Updating the Opeshift Rest Client to 0.3.0

lib/binary-build.js
* The interval that checks to see if the build has completed will now check if there is a Failed Status
* A Failed status will then clear the interval and Reject that promise, which will Stop the whole process
for #8
=> Handle more than just a Complete build status

lib/binary-build.js
When exponentially increasing the wait times, they can get really really long after a while. Linear time increase by 200ms for each loop makes more sense. We'll end up with several initial checks that will certainly fail the first few times through the loop, no matter how fast the local host is. But when working with openshift online, this approach seems to work better.
Fixes: #60 
Connects to: #60
=> fix: increase build wait times linearly

lib/definitions/container.js
I noticed that in the code that puts together the deployment config, for the container image, i was using the docker image repo as the name, which was something like this:  "172.30.1.1:5000/namespace/project-name" instead of just the project-name
everything still works, so i'm not sure why i had that like that before
=> fix: container image name should be the project name

README.md, lib/resource-loader.js, test/resource-loader-test.js
A small change, but it is important.
Templates should now use the `${KEY}` for parameters
and nodeshift users should do `nodeshift -d KEY=VALUE` 
connects to #103
=> fix: Template parameters should be inline with the openshift templates.

bin/nodeshift
this adds 9.x to the choices array for specifying nodeVersion
=> update: allow node 9.x to be specified

lib/definitions/deployment-config-spec.js, test/definitions-tests/deployment-config-spec-test.js
value is set at 2, which will keep the last 3 replication controllers
fixes #118 
connects to #118
=> update: add a default revision history limit for deployments.

README.md, bin/nodeshift, lib/nodeshift-config.js, package.json, test/nodeshift-config-test.js, test/resource-loader-test.js
i don't think there is a need to have the `--nodeshiftDirectory` options.
this only changed the name of the directory, not the actual location.
=> Remove nodeshiftdir option

bin/cli.js, bin/nodeshift
It's debatable whether this is a great improvement. I will adjust it
if it turns out to be not ideal. Now, when a user is not logged in,
the CLI writes the caught exception message and status code to
the output log. It would be ideal if we could determinen whether the
user was already logged in before making a remote call, however, so
that we can make the output nicer looking. In any case, here is what
the error looks like now.
```sh
~/s/nodejs-rest-http (master $=) nodeshift --osc.strictSSL=false .
2017-11-16T16:58:53.841Z INFO loading configuration
2017-11-16T16:58:53.867Z INFO using namespace myproject at https://192.168.99.100:8443
2017-11-16T16:58:53.871Z INFO enriching Deployment resource
2017-11-16T16:58:53.873Z INFO enriching Route resource
2017-11-16T16:58:53.874Z INFO enriching …
```
=> src: improve log message when user is not logged in

README.md, bin/cli.js, bin/nodeshift, lib/apply-resources.js, lib/deployment-config.js, lib/goals/build.js, lib/goals/undeploy.js, test/cli-test.js
This change adds a new command line option, `--metadata.out` which can have three possible values `stdout`, `false` or `<filename>`. When specified as `stdout` or `<filename>` the returned `JSON` from the `oc` REST calls is written to the specified output location.
Fixes: https://github.com/bucharest-gold/nodeshift/issues/76
connects to #76
=> src: return an object of metadata from oc calls

bin/nodeshift
It's a timing thing. We can't `require()` the log until the options have been processed.
Fixes: https://github.com/bucharest-gold/nodeshift/issues/154
Connects to: https://github.com/bucharest-gold/nodeshift/issues/154
=> fix: make --quiet flag work again

lib/binary-build.js, lib/build-watcher.js
fixes #164 
Basically just pinging the pod log endpoint with a decay, then once we get a 200 response, we stream the log
connects to #164
=> fix: make sure the pod is initialized first before trying to get the log

lib/enrich-resources.js, lib/resource-enrichers/health-check-enricher.js, test/enrich-resources-test.js, test/enricher-tests/health-check-enricher-test.js
* Checks to see if the kube-probe module is in the user package.json, if so, then some default liveness and readiness probe stuff is
added to the DeploymentConfig, if it is not already added by the user.
fixes #102
=> WIP - feat(enricher): Addition of a Health Check Enricher.

lib/resource-enrichers/default-enrichers.json
I forgot to undeploy my previous application when i was testing the enricher loader out, so when i finally did, i couldn't deploy since there was an error with the creation of the deployment config.
this fixes that.  doesn't affect 1.1.0,  just when doing the npm link to master
=> fix: label enricher should be called labels not label

lib/docker-archiver.js, lib/helpers.js, test/docker-archiver-test.js, test/helpers-test.js
* If a projectLocation was overriden, it was not being used when checking for the files it should be loading.  The archive creator was also not paying attention to the projectLocation property.
fixes #188
=> fix: projectLocation should be set correctly.

bin/nodeshift, lib/nodeshift-config.js, test/nodeshift-config-test.js
Attempting to deploy an application that fails to meet openshift's
naming rules will result in misleading error messages being returned.
This commit addresses the issue by verifying the package.name is
compliant with openshift's naming restrictions.
See issue #211
=> add package name sanitisation

README.md, bin/nodeshift, index.js, lib/definitions/container.js, lib/definitions/route-spec.js, lib/nodeshift-config.js, lib/resource-enrichers/health-check-enricher.js, lib/resource-enrichers/service-enricher.js, test/definitions-tests/container-test.js, test/definitions-tests/route-spec-test.js, test/enricher-tests/health-check-enricher-test.js, test/enricher-tests/service-enricher-test.js, test/nodeshift-config-test.js
In the Service, DeploymentConfig, Route and Health Check Enricher, the port and targetPort values were hardcoded to 8080.
This change adds the --deploy.port flag so a user can specify a port if they want.  defaults to 8080
The enrichers for the aforementioned descriptors will now use that port value
fixes #216
=> fix: remove the hardcoded 8080 for ports.

lib/resource-enrichers/service-enricher.js, test/enricher-tests/service-enricher-test.js
I'm not sure if we should provide a configuration option for this or not. I'm also not sure what the behavior would be if some other value was already specified in a `.nodeshift/service.yml` file.
fixes #183
=> fix: add a name (http) to the service port

README.md, bin/nodeshift, index.js, lib/resource-enrichers/default-enrichers.json, lib/resource-enrichers/deployment-env-enricher.js, test/enricher-tests/deployment-env-enricher-test.js
This will allow users to pass in environment variables that should be added to a deployment config.
ex: nodeshift --deploy.env NODE_ENV=development
If a deployment.yaml in the .nodeshift directory already exists with environment variables, they will be merged together
If there are duplicate vars, the ones passed in from the cli/api will take precedence.
fixes #223
=> feat: add the --deploy.env flag

bin/nodeshift, index.js, lib/build-config.js, lib/definitions/build-strategy.js, test/build-strategy-test.js
This also deprecates the use of the --nodeVersion flag, which will be removed in the 2.0 version.
fixes #256
=> feat: add the imageTag flag.

.travis.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, bin/nodeshift, index.js, lib/definitions/build-strategy.js, package.json, scripts/publish-docs.sh, test/build-strategy-test.js, test/definitions-tests/build-strategy-test.js
BREAKING CHANGE: this now uses the nodeshift/centos7-s2i-nodejs image by default. This should be a semver major change.
fixes #268
=> feat: update references of bucharest-gold to use the nodeshift namespace

bin/nodeshift, package.json
Simple one, but caught me out by deploying my project into the wrong namespace 😆
=> fix: namespace.name spelling/parsing error

README.md, bin/nodeshift, index.js, lib/definitions/build-strategy.js, test/build-strategy-test.js, test/definitions-tests/build-strategy-test.js
* This has been marked as deprecated in 1.x and can be removed.
fixes #281
=> feat: BREAKING CHANGE: remove the nodeVersion flag.

README.md, bin/nodeshift, index.js, lib/nodeshift-config.js, test/nodeshift-config-test.js
Just doing `--namespace=name` has been deprecated for a while and needs to be removed. 
It is recommended to use the format `--namespace.name`
connects to #282
=> remove the string version of the namespace flag

README.md, bin/nodeshift, index.js, lib/build-config.js, lib/definitions/container.js, lib/definitions/deployment-config-spec.js, lib/image-stream.js, lib/nodeshift-config.js, test/definitions-tests/deployment-config-spec-test.js, test/image-stream-test.js, test/nodeshift-config-test.js
fixes #337
@lance when you get a chance,  you want to test this out.
I still need to added tests and update the readme and and stuff.  but the functionality should all be there
there are now  `--outputImageStream` and `--outputImageStreamTag`  flags to specify the different output stream names and tag
=> feat: change the output Image Stream name and tag

bin/nodeshift, package.json, test/enricher-tests/git-info-enricher-test.js
* since the --fix flag was being run, we weren't getting errors on CI that linting was broken.  When i was trying to do a release, i noticed that there were some un staged files after doing the release script.
* removing the --fix flag, so we don't get false positives
=> chore: remove eslint fix by default.

lib/build-config.js, lib/resource-enrichers/default-enrichers.json, lib/resource-enrichers/runtime-label-enricher.js, test/enricher-tests/runtime-label-enricher-test.js
* This adds more labels to the created resources to better identify that this is a Node.js application in the Developer Topology view in Openshift 4.2
* THere are also labels added to the BuildConfig, that allows for better ux when looking at the topolgy view.
fixes #374
=> feat(enricher): add runtime labels to resources.

README.md, lib/nodeshift-config.js, package-lock.json, package.json, test/nodeshift-config-test.js
This allows a user to pass in a new location for a kubernetes/openshift configuration file.
fixes #341, #373
=> feat: pass in a non-default configLocation.

lib/helpers.js, test/helpers-test.js
The most recent version(1.0.3) of mkdirp actual returns a promise, so there is no need to return a promise now
fixes #411
=> fix: promisifying the newest release of mkdirp breaks mkdirp.

README.md, bin/nodeshift, index.js, lib/build-config.js, lib/definitions/build-strategy.js, lib/nodeshift-config.js, test/build-config-test.js, test/definitions-tests/build-strategy-test.js, test/nodeshift-config-test.js
* This adds a new flag `build.strategy` which takes the values Docker or Source.  default to Source.
* Source will build with an s2i image, while Docker will use the Dockerfile from the application to build.
To use the Docker strat, you would do `npx nodeshift --build.strategy=Docker`
For testing this out,  i've been using CRC,  and this sample dockerized node app, https://github.com/nodeshift-starters/basic-node-app-dockerized
=> feat(build-strategy): Add Docker build strategy

README.md, bin/nodeshift, index.js, lib/enrich-resources.js, lib/goals/apply-resources.js, lib/goals/resource.js, lib/goals/undeploy.js, lib/knative-serving-service.js, lib/nodeshift-config.js, lib/resource-enrichers/knative-enrichers.json, lib/resource-enrichers/knative-service-enricher.js, lib/resource-loader.js, package-lock.json, package.json, test/enrich-resources-test.js, test/enricher-tests/knative-serving-service-enricher-test.js, test/goals/apply-resources-test.js, test/goals/resource-test.js, test/goals/undeploy-test.js, test/knative-serving-service-test.js
This PR starts to add the ability for nodeshift to deploy a knative serving service.
It is a work in progress,  but the happy path works here.
using the nodejs-rest-http starter and code ready containers with the serverless operator installed and setup.  i was able to do `nodeshift --knative=true` with out having to change the starter app.
For a deploy, the first part(build) is unchanged, the "apply-resource" part, which is the second phase of a nodeshift deploy, has been updated to only create a knative serving service that points to the image that was just built in the first step.  
If an application has a `.nodeshift` directory with resource files that are not related to knative,  they are ignored
=> Knative Serving Deployment

package-lock.json, package.json
* This will fix an issue where you couldn't pass a nomral javascript kubernetes config object
=> chore: update openshift-rest-client to 4.1.1

lib/helpers.js, lib/project-archiver.js, package-lock.json, package.json, test/helpers-test.js
This PR adds .gitignore file support in nodeshift's project archiver. #460 
Two new NPM packages have been used:
- **parse-gitignore**: transforms .gitignore's contents into a javascript array.
- **minimatch**: performs some filename checks according to given rules (same module **NPM** uses internally for the same job)
> Maybe we can work out some custom implementation for the .gitignore parser if we want to reduce the amount of 3rd party modules that we use.
**.dockerignore** support should be 2-3 extra lines of code since the core implementation is done.
@lholmquist @helio-frota I'm just pinging you here cause I can't add any reviewers for this PR
If you guys think everything is OK I'll continue with the .dockerignore support and tests.
=> Adding .gitignore support in project-archiver

lib/helpers.js, lib/knative-serving-service.js, lib/resource-enrichers/knative-service-enricher.js, test/knative-serving-service-test.js
* This adds in a generated appId label to the service template metadata to create a new revision on each deployment
fixes #466 
some tests still need to be added
=> feat(knative): Each deploy should create a new revision.

README.md, bin/nodeshift, index.js, lib/deployment.js, lib/enrich-resources.js, lib/goals/apply-resources.js, lib/goals/undeploy.js, lib/resource-enrichers/deployment-enricher.js, lib/resource-enrichers/deployment-enrichers.json, test/deployment-test.js, test/enrich-resources-test.js, test/goals/apply-resources-test.js, test/goals/undeploy-test.js
This adds the ability for a user to use a Deployment instead of a DeploymentConfig using the `--useDeployment` flag when doing a deployment.
This flag can also be used during the `resource`, `apply-resource`, `deploy` and `undeploy` goals
fixes #476
=> feat: Nodeshift should be able to use a Deployment type

README.md, bin/nodeshift, index.js, lib/config/nodeshift-config.js, package-lock.json, package.json, test/config-tests/nodeshift-config-test.js
The openshiftt Rest client already has the ability to specify a username/password/api server url combo instead of using the default `~/.kube/config` file.
This PR adds the ability to now pass those options in through the cli and API
New options added:
`username`, `password` , `apiServer` and `insecure`.
Since this flow doesn't get any existing kube configs that might be local,  it will not get the current namespace/project that a user might be on.  So by default it will just use the `default` namespace, but by using the `namespace` flag, it can easily be changed.  
If using Code Ready Containers(CRC), the cli command might look something like this:
`$ nodeshift --apiServer https://api.crc.testing:6443 --username developer --password developer --insecure --namespace.name nodejs-examples` …
=> Use passed in credentials to deploy instead of getting the local kube config

README.md, bin/nodeshift, index.js, lib/config/nodeshift-config.js, test/config-tests/nodeshift-config-test.js
the flag `server` is more inline with what Openshift and the `oc` command use
=> feat: deprecate apiServer and replace with server

README.md, bin/nodeshift, index.js, lib/config/nodeshift-config.js, package-lock.json, package.json, test/config-tests/nodeshift-config-test.js
This adds the `token` flag,  which allows a user to pass a auth token to the openshift rest client.
This also updates the Openshift Rest Client to the latest(5.1.0) which includes the token feature
=> feat:  add a token flag to pass in an auth token for API calls

README.md, bin/nodeshift, index.js, lib/definitions/build-strategy.js, test/definitions-tests/build-strategy-test.js
BREAKING CHANGE: This updates the default builder image to use Node 14 instead of Node 10
=> feat!: Default to Node 14 for the build image

lib/config/nodeshift-config.js, test/config-tests/nodeshift-config-test.js
* This modifies the logic that was used to determine if an applications package name was valid.  Previously, nodeshift would error when using scoped packages.  Since @org/pkg is valid in npm,  this is now valid with nodeshift.  scoped package names will be updated to org-pkg for the Openshift Objects the CLI creates.
fixes #538
=> fix(config): Allow scoped applications in the package name.

bin/nodeshift, lib/config/nodeshift-config.js, lib/definitions/build-strategy.js, lib/helpers.js, lib/resource-enrichers/default-enrichers.json, lib/resource-enrichers/deployment-enrichers.json, lib/resource-enrichers/metering-enricher.js, test/definitions-tests/build-strategy-test.js, test/enricher-tests/metering-enricher-test.js
* The new flag is `--rh-metering`.  can also be used as `--rh-metering.component-version=NODE_VERSION`
* This is currently an undocumented feature since it is more for those using Red Hat Runtimes build of Node.js
=> feat(enricher): Adds the rh-metering flag for adding Red Hat Runtimes metering to your application.

README.md, bin/cli.js, bin/nodeshift, index.js, lib/config/login-config.js, lib/config/nodeshift-config.js, test/cli-test.js, test/config-tests/login-config-test.js, test/config-tests/nodeshift-config-test.js, test/index-test.js
This PR adds the `login` command.  It is meant to be run first with either a username/password or a valid token and the api server of the cluster
something like this: `nodeshift login --token=12345 --server=https.......`  then run `nodeshift deploy`.  While you can specify all those argument flags with the deploy command,  this cleans things up a bit
The new login command will write the authtoken and the api server to a login.json file that lives in `PROJECT_LOCATION/tmp/nodeshift/config/login.json`.  this tmp directory is also used in the build and deploy steps,  and should be gitignored.
CLI Usage - Login: 
```
$ nodeshift login --username=developer --password=password --server=https://api.server
or 
$ nodeshift login --token=12345 --server=https://api.server
```
CLI Usage - Logout
``` …
```
=> feat: nodeshift login with cli

bin/nodeshift, index.js, lib/definitions/route-spec.js, test/definitions-tests/route-spec-test.js
When using export, a Route is generated, but there was no way to define
the Alias/DNS that points to the service.
=> add exposeHost option

bin/nodeshift
flags `--build.env` and `--deploy.env` are not present in the cli help,
though the options are supported and documented in the readme
=> document missing options in cli help

bin/cli.js, index.js
This adds a method to the API where a user can call `.getNodeshiftConfig` and get back the current config nodeshift uses.
=> feat: add getNodeshiftConfig method

lib/ingress.js, test/ingress-test.js
The current api `extensions.v1beta1` is being deprecated, this updates to the newest.
see https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
=> chore: update ingress to use the v1 api

examples/sample-project-no-name/package.json, lib/config/nodeshift-config.js, test/config-tests/nodeshift-config-test.js
This PR adds a check for the name field in the package.json.
The second commit removes some rogue console.logs
=> Check for a package name first

.github/workflows/nodejs-ci-action.yml, README.md, package-lock.json, package.json
This would require a semver major bump so may want to time landing/releasing appropriately.
=> chore: drop Node.js 12

lib/definitions/route-spec.js, test/definitions-tests/route-spec-test.js
This was discovered using the Openshift Sandbox, where the application would only load on the insecure(http) route and not on the secure(https) route.  When creating a route through openshift, this part of the tls portion of the route spec gets created automatically.
=> fix: non-secure routes should redirect to the secure version.

README.md, bin/nodeshift, docs/assets/anchor.js, docs/index.html, index.js, lib/enrich-resources.js, lib/resource-enrichers/default-enrichers.json, lib/resource-enrichers/deployment-config-enrichers.json, lib/resource-enrichers/deployment-enrichers.json, lib/resource-enrichers/deployment-env-enricher.js, test/enrich-resources-test.js
This is a breaking change that removed the "--useDeployment" flag and replaces it with the "--useDeploymentConfig" flag making the Deployment resource the default
A DeploymentConfig has been deprecated since Openshift 4.14 and it is recommended to use a Deployment resource for new applications.
see https://docs.openshift.com/container-platform/4.18/applications/deployments/what-deployments-are.html
=> feat!: make Deployment the default resource

lib/config/nodeshift-config.js, test/config-tests/nodeshift-config-test.js
When using the source strategy the buildName suffix is s2i and if using the Docker strategy the suffix should use docker
=> fix: add the correct buildname suffix

.github/workflows/release-please.yml
THe previous version was using Node 16 so tests were failing and the automated publish was broken
=> chore: update the release please setup action to use node 22
