nodeshift/nodeshift

bin/nodeshift
package-lock.json
package.json

* Adds in options, version and help for the command line.
connects to #18

adding commander to the cli

---

bin/nodeshift
package-lock.json
package.json

Commander has a lot of usage, but hasn't been maintained. Going with a more modern cli library
connects to #32

removing commander. adding yargs

---

lib/binary-build.js
lib/build-watcher.js

Move build watcher code to another internal module

---

package.json

add a ci npm script that runs linting during tests. fixes #49

---

.travis.yml
bin/cli.js
bin/nodeshift
lib/binary-build.js
lib/build-config.js
lib/deployment-config.js
lib/docker-archiver.js
lib/image-stream.js
lib/nodeshift-config.js
lib/resource-loader.js
lib/routes.js
lib/services.js
package.json
test/nodeshift-config-test.js

Using async/await simplifies the code quite a bit, and since this is a CLI and not typically embedded software, requiring node 7.6 or greater seems like it should not be a problem.

Use async/await where appropriate

---

bin/cli.js
bin/nodeshift
lib/binary-build.js
lib/build-config.js
lib/build-watcher.js
lib/common-log.js
lib/deployment-config.js
lib/docker-archiver.js
lib/image-stream.js
lib/nodeshift-config.js
lib/resource-loader.js
lib/routes.js
lib/services.js
package.json
test/nodeshift-config-test.js

I've added a module called `common-log` which standardizes the output, uses `chalk`, adds a timestamp.
Not sure if we really want the timestamp.
Connects to #23

enhance: make logging nicer looking and consistent

---

lib/docker-archiver.js
lib/helpers.js
test/helpers-test.js

src: warning if a file doesn't exist

---

bin/nodeshift
lib/nodeshift-config.js
package-lock.json
test/nodeshift-config-test.js

new config loader options

---

lib/secrets.js
test/secrets-test.js

* The secret name should come from the credentials.yml file that is supplied, *not* the projectName
fixes #73 
connects to #73

fix(secrets): fix bug with secret naming.

---

bin/nodeshift
lib/resource-loader.js
test/resource-loader-test.js

first pass at string subs,  need to add a test first

---

lib/resource-loader.js
test/resource-loader-test.js

this adds the ability to also read in .yaml files instead of just the .yml files.
First commit here is removing the test.skip that i forgot to remove

also read yaml

---

README.md
bin/nodeshift
lib/build-config.js
lib/image-stream.js
package-lock.json
package.json
test/build-config-test.js
test/image-stream-test.js

connects to #80 
i'll be adding things as they get created

WIP - recreate flag

---

bin/cli.js
lib/apply-resources.js
lib/deployment-config.js
lib/docker-archiver.js
lib/enrich-resources.js
lib/helpers.js
lib/resource-enrichers/deployment-config-enricher.js
lib/resource-enrichers/route-enricher.js
lib/resource-enrichers/secret-enricher.js
lib/resource-enrichers/service-enricher.js
lib/resource-writer.js
lib/routes.js
lib/secrets.js
lib/services.js
package-lock.json
package.json
test/docker-archiver-test.js
test/helpers-test.js

WIP - 111 create resources

---

bin/nodeshift
lib/build-config.js
lib/definitions/build-strategy.js
package.json
test/definitions-tests/build-strategy-test.js

using the flag `--build.forcePull`

update: add the forcePull options to the build strategy.  fixes #114

---

README.md
bin/cli.js
bin/nodeshift
index.js
lib/goals/build.js
lib/goals/resource.js
test/cli-test.js
test/index-test.js

* defaults to running everything
* resource - command to just generate the resource yaml/json template file from #111
* apply-resource - command that runs the resource command, then pushes that up to your cluster
fixes #81 
sort of also does parts of #4 
connects to #81

update: Addition of some commands to run parts of nodeshift

---

bin/cli.js
bin/nodeshift
lib/apply-resources.js
lib/deployment-config.js
lib/goals/undeploy.js
test/cli-test.js
test/deployment-config-test.js
test/goals/undeploy-test.js

WIP - undeploy command

---

index.js
test/index-test.js

enhancement: add undeploy to the public api

---

bin/cli.js
bin/nodeshift
index.js
test/cli-test.js
test/index-test.js

* This command will run the build goal
* This includes, archiving your code, creating a buildconfig and imagestream and pushing the archive to the cluster
the last Part of #4
connects to #4

enhancement:  add a build command.

---

package-lock.json
package.json

chore(package): update nsp to version 3.1.0

---

lib/resource-loader.js
test/resource-loader-test.js

update: application file descriptors can now be json,  fixes #91

---

lib/binary-build.js
lib/build.js

These are pretty minor nits, but I came across them as I was working on the logging output.

src: make a couple of minor style changes

---

package.json

build: change prepublish script to 'prepare'

---

lib/enrich-resources.js
lib/resource-enrichers/git-info-enricher.js
package-lock.json
package.json
test/enrich-resources-test.js
test/enricher-tests/git-info-enricher-test.js

initial annotaion git stuff with no tests

---

index.js
test/index-test.js

chore: remove deprecated deployApplication method from API.  fixes #145

---

README.md
bin/nodeshift
lib/nodeshift-config.js
test/nodeshift-config-test.js

WIP - start of README overhaul

---

bin/nodeshift

Connects to: https://github.com/bucharest-gold/nodeshift/issues/156
Fixes: https://github.com/bucharest-gold/nodeshift/issues/156

fix: actually obey 'ignore' in the --metadata.out option

---

lib/enrich-resources.js
lib/load-enrichers.js
lib/resource-enrichers/default-enrichers.json
lib/resource-enrichers/deployment-config-enricher.js
lib/resource-enrichers/git-info-enricher.js
lib/resource-enrichers/health-check-enricher.js
lib/resource-enrichers/labels-enricher.js
lib/resource-enrichers/service-enricher.js
test/enrich-resources-test.js
test/enricher-tests/deployment-config-enricher-test.js
test/enricher-tests/git-info-enricher-test.js
test/enricher-tests/health-check-enricher-test.js
test/enricher-tests/labels-enricher-test.js
test/enricher-tests/route-enricher-test.js
test/enricher-tests/service-enricher-test.js
test/load-enrichers-test.js

WIP for #149

---

lib/resource-enrichers/default-enrichers.json

so it seems i have an issue with remembering if things have an s on them or not.  FFS

fix: default enrichers should be named properly

---

lib/enrich-resources.js
lib/goals/resource.js
lib/resource-enrichers/deployment-config-enricher.js
lib/resource-enrichers/git-info-enricher.js
lib/resource-enrichers/health-check-enricher.js
lib/resource-enrichers/labels-enricher.js
lib/resource-enrichers/route-enricher.js
lib/resource-enrichers/service-enricher.js
test/enrich-resources-test.js
test/enricher-tests/deployment-config-enricher-test.js
test/enricher-tests/git-info-enricher-test.js
test/enricher-tests/health-check-enricher-test.js
test/enricher-tests/labels-enricher-test.js
test/enricher-tests/route-enricher-test.js
test/enricher-tests/service-enricher-test.js

* Each enrhicher now returns a Promise
fixes #149

update(enrichers): Make all enrichers Async

---

bin/nodeshift

fixes #167 
@lance @helio-frota mind taking a look
The warning message that it emits probably could be better, hence the review :)
I was hoping that yargs would have something that allowed optional choices, but i didn't see anything
connects #167

enhancement: Allow the nodeVersion option to use staging tags.

---

README.md
bin/nodeshift
lib/build-config.js
lib/definitions/build-strategy.js
test/definitions-tests/build-strategy-test.js

This will allow a user to specify a different s2i image to use in their builds
fixes #178

WIP - feat: adds the --dockerImage flag.

---

bin/nodeshift

https://github.com/yargs/yargs/blob/master/CHANGELOG.md#features-4

src: help and version enabled by default since yargs 9

---

README.md
bin/nodeshift
index.js
lib/definitions/route-spec.js
lib/resource-enrichers/route-enricher.js
package-lock.json
test/enricher-tests/route-enricher-test.js

expose option to create a default route if needed

---

lib/apply-resources.js
lib/goals/undeploy.js
lib/ingress.js
lib/resource-loader.js
test/apply-resources-test.js
test/goals/undeploy-test.js
test/ingress-test.js

There is no enrichment happeing here, for the moment you need to create the full Ingress yaml.
fixes #238

WIP - feat: create an Ingress if there is one in the .nodeshift directory

---

README.md
bin/nodeshift
lib/build-config.js
lib/definitions/build-strategy.js
test/definitions-tests/build-strategy-test.js

feat: add a flag, --build.incremental, that turns on incremental builds.

---

README.md
bin/cli.js
bin/nodeshift
lib/binary-build.js
lib/build-watcher.js
lib/goals/apply-resources.js
lib/goals/watch-spawn.js
lib/goals/watch-sync.js
lib/helpers.js
test/cli-test.js
test/goals/apply-resources-test.js
test/goals/watch-sync-test.js

The first commit is just moving some files around.
The other commits are the new feature.
This adds a "watch" command, which will find the most recent pod for your project, wait until it is ready, then "oc rsync" to it.  The `oc rsync` command will watch for files to change and then sync your local files with the files of the running pod
connects to #262

local server file reload

---

lib/resource-enrichers/deployment-config-enricher.js
package.json
test/enricher-tests/deployment-config-enricher-test.js

fix: deployment enricher should also look for DeploymentConfig kind

---

lib/goals/watch-sync.js

fixes #274 
@lance if you wouldn't mind giving this a little test

fix: add the --no-perm=true option to the oc rsync command

---

README.md
bin/cli.js
bin/nodeshift
index.js
lib/definitions/deployment-config-spec.js
lib/namespace.js
lib/nodeshift-config.js
test/cli-test.js
test/definitions-tests/deployment-config-spec-test.js
test/namespace-test.js
test/nodeshift-config-test.js

Create a namespace/project if one doesn't exist when using the --namespace flag

---

lib/build-config.js
lib/image-stream.js
test/build-config-test.js
test/image-stream-test.js

fix: build.recreate should also check the string version of true/false

---

package-lock.json
package.json

chore: remove the unused request module

---

.circleci/config.yml
.travis.yml

chore: add node 10 and node 12 to the CI jobs.

---

package-lock.json
package.json

chore: remove unrequired eslint-plugin-react

---

README.md
bin/nodeshift
lib/build-config.js
lib/definitions/build-strategy.js
test/definitions-tests/build-strategy-test.js

I'm re-opening the PR from the new branch 'web-app-flag'. Still WIP but the linting error is fixed and I also updated the docs, so the only thing left is writing the tests :)

Adding web-app flag

---

package.json

@lholmquist this PR changes the node's engine version from 8+ to 10+. Do I also have to do the release process for the semver-major update we talked about and add it in this PR or you'll do it after the PR merge ??

Engine parameter targets node 10+

---

lib/helpers.js
lib/utils/rmrf.js
package-lock.json
package.json
test/helpers-test.js
test/utils-test.js

This new PR about the rimraf replacement consists of:
- Some bug fixes for rmrf module that didn't exist in the previous PR
- 100% test coverage about the custom module

Replacing rimraf with custom module

---

test/helpers-test.js

Test coverage for helpers

---

test/common-log-test.js

Improve test coverage for common-log

---

package.json
test/helpers-test.js

This is about what @helio-frota talked about in our team meeting about some redundant entries in package.json

Removing redundant entries

---

README.md
bin/nodeshift

These 2 commits are just some small maintenance updates.
The readme update gets rid of the greenkeepr badge, and shows how to use with npx
The second commit moves the `require(cli)` up to the top of the file so it is easier to debug things when using the inspector

Maintenance updates

---

README.md

Updating docs with project archiver info

---

lib/nodeshift-config.js

This commit is to help with debug branch.
It basically assigns the result to a variable and then returns it.

chore: minor typos and variable assignment

---

.github/workflows/api-docs.yml
.github/workflows/release-please.yml

chore: add gh actions for releasing and doc generation.

---

README.md
bin/nodeshift
index.js
lib/resource-loader.js
test/resource-loader-test.js

This PR corresponds to a feature request in #491

Define a subdirectory below .nodeshift/ that indicates where Openshift resources are stored

---

bin/nodeshift

src: this workaround fix the behavior with quiet flag

---

lib/config/nodeshift-config.js

* This was due to the options.dockerImage being mispelled

fix: dockerImage was undefined.

---

.github/workflows/nodejs-ci-action.yml
.github/workflows/release-please.yml
CONTRIBUTING.md
README.md
docs/assets/anchor.js
docs/index.html
test/enricher-tests/git-info-enricher-test.js

Signed-off-by: Michael Dawson <mdawson@devrus.com>

move to main for primary branch

---

index.d.ts
index.js
package-lock.json
package.json
test/helpers-test.js
tsconfig.json

This adds typesctript types based on the JSDoc

feat: add typescript typings

---

lib/helpers.js
package-lock.json
package.json

version 9 changed to only having named exports
fixes #702

fix: update minimatch to the latest.

---

bin/nodeshift
lib/config/nodeshift-config.js
test/config-tests/nodeshift-config-test.js

Currently defaults to the name in the package.json

feat: add flag to change the name.

---

.github/workflows/nodejs-ci-action.yml
package-lock.json
package.json

feat!: remove Node 18 support
